# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define :pxe_server, autostart: false do |pxe_server|

    pxe_server.vm.box = "ubuntu/xenial64"
    pxe_server.vm.hostname = "pxe-server"
    pxe_server.vm.synced_folder '.', '/vagrant', disabled: true
    pxe_server.vm.synced_folder '../build-pxe-live-image/releases/', '/pxe-live-image/'
    pxe_server.vm.network "private_network", ip: "192.168.0.254", virtualbox__intnet: "pxe_lab_network"
    pxe_server.ssh.forward_agent = true

    pxe_server.vm.provider :virtualbox do |vb|
      vb.memory = '1024'
      vb.cpus = '1'
    end

    pxe_server.vm.provision "file", source: "assets/", destination: "/home/vagrant/"

$script = <<SCRIPT
set -e
sudo cp assets/hooktftp/hooktftp /usr/local/bin/hooktftp
sudo chmod ugo+rwx /usr/local/bin/hooktftp
sudo cp assets/hooktftp/hooktftp.service /etc/systemd/system/hooktftp.service
sudo cp assets/hooktftp/hooktftp.yml /etc/hooktftp.yml

sudo mkdir -p /var/lib/tftpboot/
sudo cp assets/ldlinux.c32 /pxe-live-image/ldlinux.c32
sudo cp assets/pxelinux.0 /pxe-live-image/pxelinux.0
sudo mkdir -p /pxe-live-image/pxelinux.cfg/
sudo cp assets/pxelinux.cfg /pxe-live-image/pxelinux.cfg/default

sudo mkdir -p /opt/kea/
sudo cp assets/kea/docker-compose.yml /opt/kea/
sudo cp assets/kea/kea-config.json /opt/kea/

sudo apt-get update -y
sudo apt-get install -y apt-transport-https ca-certificates curl gnupg2 python3-pip apache2
sudo echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable" > /etc/apt/sources.list.d/docker.list
sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo apt-get update -y
sudo apt-get install -y docker-ce
sudo pip3 install --upgrade pip
sudo pip3 install docker-compose

sudo systemctl enable hooktftp.service
sudo systemctl start hooktftp.service
(cd /opt/kea/ && sudo docker-compose up -d)
sudo chmod ugo+rwX /pxe-live-image/*
sudo cat > /etc/apache2/sites-available/000-default.conf <<EOL
<VirtualHost *:80>
	DocumentRoot /pxe-live-image/
</VirtualHost>
<Directory /pxe-live-image/>
	Options Indexes FollowSymLinks
	AllowOverride None
	Require all granted
</Directory>
EOL
sudo apache2ctl restart
SCRIPT

     pxe_server.vm.provision "shell", inline: $script
  end

  config.vm.define :blank_server_1, autostart: false do |blank_server|
    ip = "192.168.0.11"

    blank_server.vm.box = "TimGesekus/pxe-boot"
    blank_server.vm.boot_timeout = 1
    blank_server.vm.network "private_network", :adapter=>1, ip: ip, :mac => "0800278E158A" , auto_config: false, virtualbox__intnet: "pxe_lab_network"
    blank_server.vm.synced_folder '.', '/vagrant', disabled: true
    blank_server.ssh.insert_key = "false"
    blank_server.vm.provider "virtualbox" do |vb, override|
        vb.gui = true
        # Chipset needs to be piix3, otherwise the machine wont boot properly.
        vb.customize [
          "modifyvm", :id,
          "--pae", "off",
          "--chipset", "piix3",
          '--boot1', 'net',
          '--boot2', 'disk',
          '--boot3', 'none',
          '--boot4', 'none'
        ]
    end
  end
end
