# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "builder", autostart: false do |builder|
      builder.vm.box = 'ubuntu/xenial64'
      builder.vm.provision "shell",
        inline: "
        apt-get -qqq update
        apt-get -qqq install \\
            apt-transport-https \\
            ca-certificates \\
            curl \\
            software-properties-common
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        apt-key fingerprint 0EBFCD88
        add-apt-repository \\
           \"deb [arch=amd64] https://download.docker.com/linux/ubuntu \\
             $(lsb_release -cs) \\
             stable\"
        apt-get -qqq update
        apt-get -qqq install docker-ce
      "
  end
end
